### ISSUE TITLE
PyTorch microbenchmark fails to run using 7900XTX

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/pytorch#1276]
### 🐛 Describe the bug

I'm trying to get some performance numbers for 7900XTX in PyTorch. But I have not been able to run any standard benchmark.

Using a fresh Ubuntu 22.04 docker container, I installed ROCm 5.6.1. Then, I installed PyTorch nightly build using the following command
> pip3 install --pre --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.6

Then cloned the micro benchmark code from 
>  git clone https://github.com/ROCmSoftwarePlatform/pytorch-micro-benchmarking

The first benchmark I ran failed with the following error.

>root@rocm-ubuntu:~/pytorch-micro-benchmarking# python3 micro_benchmarking_pytorch.py --network resnet50
INFO: running forward and backward for warmup.
Traceback (most recent call last):
  File "/root/pytorch-micro-benchmarking/micro_benchmarking_pytorch.py", line 405, in <module>
    main()
  File "/root/pytorch-micro-benchmarking/micro_benchmarking_pytorch.py", line 367, in main
    run_benchmarking_wrapper(copy.deepcopy(args))
  File "/root/pytorch-micro-benchmarking/micro_benchmarking_pytorch.py", line 190, in run_benchmarking_wrapper
    run_benchmarking(0, params)
  File "/root/pytorch-micro-benchmarking/micro_benchmarking_pytorch.py", line 283, in run_benchmarking
    forwardbackward(inp, optimizer, network, target, amp_opt_level)
  File "/root/pytorch-micro-benchmarking/micro_benchmarking_pytorch.py", line 135, in forwardbackward
    out = network(inp)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py", line 278, in _forward_impl
    x = self.avgpool(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/pooling.py", line 1194, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 1228, in adaptive_avg_pool2d
    return torch._C._nn.adaptive_avg_pool2d(input, _output_size)
RuntimeError: HIP error: the operation cannot be performed in the present state
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

My goal is to run benchmarks and compare the performance with NVidia GPUs. I ran some benchmarks using TensorFlow and was able to run the benchmark even though the result showed that it still needs more optimization. However, I could not get any PyTorch benchmark to run. I tried both https://github.com/pytorch/benchmark and https://github.com/ROCmSoftwarePlatform/pytorch-micro-benchmarking. 

### Versions

```
# python collect_env.py
Collecting environment information...
PyTorch version: 2.1.0.dev20230903+rocm5.6
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.6.31061-8c743ae5d

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Radeon RX 7900 XTX
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.6.31061
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             16
On-line CPU(s) list:                0-15
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 9 3900X 12-Core Processor
CPU family:                         23
Model:                              113
Thread(s) per core:                 1
Core(s) per socket:                 16
Socket(s):                          1
Stepping:                           0
BogoMIPS:                           7599.99
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif umip rdpid arch_capabilities
Virtualization:                     AMD-V
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          1 MiB (16 instances)
L1i cache:                          1 MiB (16 instances)
L2 cache:                           8 MiB (16 instances)
L3 cache:                           256 MiB (16 instances)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-15
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.12
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-triton-rocm==2.1.0+34f8189eae
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.7
[pip3] torch==2.1.0.dev20230903+rocm5.6
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torchaudio==2.2.0.dev20230905+rocm5.6
[pip3] torchmetrics==1.1.1
[pip3] torchvision==0.16.0.dev20230905+rocm5.6
[pip3] vector-quantize-pytorch==1.7.1
[conda] Could not collect
```

**Comment by briansp2020** [comment]
Well. It turned out I can't run anything on GPU using pytorch.

```
# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.2.0.dev20230906+rocm5.6'
>>> x=torch.rand(20000000, 128, device = 'cuda')
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 431, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 595, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 347, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 137, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: HIP error: the operation cannot be performed in the present state
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

Does anyone have any idea? I was able to get TensorFlow working relatively easily with my 7900XTX. But can't seem to get pytorch running at all. :(

**Comment by briansp2020** [comment]
PyTorch nightly build for ROCm 5.6 seems broken. Nightly build for 5.5 seems to work.

**Comment by briansp2020** [comment]
After getting rid of Proxmox, things are running better. However, I can't run https://github.com/pytorch/benchmark (it won't run on my NVidia setup either)
Does anyone know of a good pytorch benchmark I can use to compare 3080ti vs 7900XTX?

**Comment by briansp2020** [comment]
Has anyone tried running FastAI using ROCm PyTorch? I got the packages to install but when running the 09 notebook (https://github.com/fastai/course22/blob/master/09-small-models-road-to-the-top-part-2.ipynb), it runs very slow and all CPU cores are 100 loaded. So, I don't think it is using the GPU at all. :(

**Comment by jithunnair-amd** [comment]
> After getting rid of Proxmox, things are running better. However, I can't run https://github.com/pytorch/benchmark (it won't run on my NVidia setup either) Does anyone know of a good pytorch benchmark I can use to compare 3080ti vs 7900XTX?

@briansp2020 Does this mean you were able to run pytorch-micro-benchmarking successfully on ROCm using ROCm5.6 nightly wheels?

**Comment by briansp2020** [comment]
No. I have not been able to run pytorch benchmark. But I think the issue I ran into was about the benchmark using NV-specific api to measure execution time.

I think my pytorch was installed fine and now runs some code using GPU. But I just found out that it's not working correctly when I tried to run fastai course notebook. It seems that ROCm pytorch still needs more work.

**Comment by briansp2020** [comment]
Ok. I was a bit confused and did not realize that I'm talking about 2 different pytorch benchmark.

I initially filed this issue when I was having problem with pytorch but I think that was my setup issue. I changed my setup and installed ROCm 5.7 which was just released. I'm now able to run pytorch code and some of them run ok using GPU. However, I think there is still major problems with ROCm pytorch, one of which is fastai problem I mentioned here (https://github.com/ROCmSoftwarePlatform/pytorch/issues/1276#issuecomment-1720712808)

As for benchmarking, https://github.com/ROCmSoftwarePlatform/pytorch-micro-benchmarking now runs
```
:~/pytorch-micro-benchmarking# python micro_benchmarking_pytorch.py --network resnet50
INFO: running forward and backward for warmup.
INFO: running the benchmark..
OK: finished running benchmark..
--------------------SUMMARY--------------------------
Microbenchmark for network : resnet50
Num devices: 1
Dtype: FP32
Mini batch size [img] : 64
Time per mini-batch : 0.18377923965454102
Throughput [img/sec] : 348.2439045906599
(pt) root@rocm:~/pytorch-micro-benchmarking# python micro_benchmarking_pytorch.py --network resnext50_32x4d
INFO: running forward and backward for warmup.
INFO: running the benchmark..
OK: finished running benchmark..
--------------------SUMMARY--------------------------
Microbenchmark for network : resnext50_32x4d
Num devices: 1
Dtype: FP32
Mini batch size [img] : 64
Time per mini-batch : 0.23627933263778686
Throughput [img/sec] : 270.8658403827099
(pt) root@rocm:~/pytorch-micro-benchmarking# python micro_benchmarking_pytorch.py --network resnext101_32x8d
INFO: running forward and backward for warmup.
INFO: running the benchmark..
OK: finished running benchmark..
--------------------SUMMARY--------------------------
Microbenchmark for network : resnext101_32x8d
Num devices: 1
Dtype: FP32
Mini batch size [img] : 64
Time per mini-batch : 0.5749702095985413
Throughput [img/sec] : 111.31011473565981
```

I'm still trying to run https://github.com/pytorch/benchmark. But I think it failed because it was using NV specific API to measure execution time.


```
# python collect_env.py
Collecting environment information...
PyTorch version: 2.2.0a0+git39ff801
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.7.31921-d1770ee1b

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Radeon RX 7900 XTX
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.7.31921
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             16
On-line CPU(s) list:                0-15
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 9 5950X 16-Core Processor
CPU family:                         25
Model:                              33
Thread(s) per core:                 1
Core(s) per socket:                 16
Socket(s):                          1
Stepping:                           2
Frequency boost:                    enabled
CPU max MHz:                        3400.0000
CPU min MHz:                        2200.0000
BogoMIPS:                           6800.18
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                     AMD-V
L1d cache:                          512 KiB (16 instances)
L1i cache:                          512 KiB (16 instances)
L2 cache:                           8 MiB (16 instances)
L3 cache:                           64 MiB (2 instances)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-15
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.1.0+34f8189eae
[pip3] torch==2.2.0a0+git39ff801
[pip3] torchaudio==2.2.0.dev20230916+rocm5.6
[pip3] torchvision==0.17.0a0+75046bd
[conda] Could not collect
```

**Comment by briansp2020** [comment]
I'm closing this since my original issue is resolved. (i.e. git clone https://github.com/ROCmSoftwarePlatform/pytorch-micro-benchmarking runs)
