### ISSUE TITLE
[GFX803] Memory Access Fault during backward propagation

### ISSUE THREAD

**Issue by Delaunay** [ROCmSoftwarePlatform/pytorch#369]
## 🐛 Bug

Memory Access Fault during backward propagation

```
> python rocm_memory_access_fault.py 
Starting Epochs
Sending to device
Preprocessing
Eval model
compute loss
backward
Memory access fault by GPU node-1 (Agent handle: 0x1992010) on address 0x54fc00000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

## To Reproduce

Run the script below

[rocm_memory_access_fault .py.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/2943906/rocm_memory_access_fault.py.txt)

## Expected behavior

Should run successfully 

## Environment

```
python collect_env.py 
Collecting environment information...
PyTorch version: 1.1.0a0+9b73dca
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.2.0-7ubuntu1) 8.2.0
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.1.0a0+9b73dca
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

```

 - Python version: 3.6
 - GPU models and configuration: Single RX580 GPU

* debug output `HIP_DB=3 HCC_SERIALIZE_KERNEL=0x6 python rocm_memory_access_fault.py > debug.txt 2>&1`
[debug.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/2943919/debug.txt)

Last lines are:
```
<<hip-api pid:17072 tid:2.1517 hipHccModuleLaunchKernel (0x5371c1000, 4096, 2, 2, 128, 1, 1, 0, stream:<null>, 0, 0x7f27e9c4ec70) @177341134910837
  hip-sync pid:17072 tid:2:ihipSyncAndResolveStream stream:<null> wait on default stream
  hip-sync pid:17072 tid:2:locking criticalData=0x7f27739a25b8 for ctx:0x7f27739a25a0.dev:0..
  hip-sync pid:17072 tid:2:syncDefaultStream 
  hip-sync pid:17072 tid:2:  syncDefaultStream depOps=0
  hip-sync pid:17072 tid:2:auto-unlocking criticalData=0x7f27739a25b8 for ctx:0x7f27739a25a0.dev:0...
  hip-sync pid:17072 tid:2:locking criticalData=0x7f2773563680 for stream:0.0..
<<hip-api pid:17072 tid:2.1517 17072 2.1517 hipLaunchKernel 'MIOpenCvBwdWrW' gridDim:{4096,2,2} groupDim:{128,1,1} sharedMem:+0 stream:0.0 @177341134967182
Memory access fault by GPU node-1 (Agent handle: 0x2054010) on address 0x550200000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

**Comment by iotamudelta** [comment]
@Delaunay can you add `MIOPEN_ENABLE_LOGGING_CMD=1`? This should print the MIOpen command causing the failure (as an miopendriver command line). If you could see if it segfaults also w/o PyTorch just in MIOpen, that'd be great!

**Comment by Delaunay** [comment]
```
backward
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 512 -H 28 -W 28 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 512 -H 28 -W 28 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 256 -H 28 -W 28 -k 512 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 128 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 128 -H 112 -W 112 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 64 -H 112 -W 112 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 64 -H 224 -W 224 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 3 -H 224 -W 224 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenConvolutionBackwardData: ./bin/MIOpenDriver conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
miopenFindConvolutionBackwardWeightsAlgorithm: ./bin/MIOpenDriver conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
Memory access fault by GPU node-1 (Agent handle: 0x1894010) on address 0x54fc00000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

Seems MIOpen is the one failing

```
setepenre@nas:~/source/MIOpen/build$ ./bin/MIOpenDriver conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpenDriver: conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 0.613340 ms (average)
Forward Convolution Verifies on CPU and GPU (1.10376e-07)
MIOpen Backward Data Conv. Algorithm: 1
GPU Kernel Time Backward Data Conv. Elapsed: 0.535073 ms (average)
Memory access fault by GPU node-1 (Agent handle: 0x55e0c0e20ba0) on address 0x504000000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

**Comment by Delaunay** [comment]
@iotamudelta  I have found another access fault that is also caused by MIOpen.
Do you want me to bundle the faults and post the issue on MIOpen repo directly ?

**Comment by iotamudelta** [comment]
@Delaunay thanks, I'll see report this also internally.

**Comment by geekboood** [comment]
@iotamudelta Do you have a timeline when this problem could be fixed? I encounter the same issue on both Tensorflow and Pytorch.

**Comment by Delaunay** [comment]
In the MIOpen thread there is an instruction to download an dev version of the opencl driver that fixes the issue.

**Comment by iotamudelta** [comment]
If it's in dev, then I'd think it should be in the next ROCm release. Does the dev version fix things for you completely?

**Comment by Delaunay** [comment]
I have not seen that issue in a while.

**Comment by iotamudelta** [comment]
@geekboood are you on ROCm 2.2? Can you confirm the dev driver fixes the issue for you? Thanks!

**Comment by geekboood** [comment]
@iotamudelta I am using ROCm 2.1 and I have just seen some solutions to roll back to ROCm 1.9.2. However, it doesn't work for me.

**Comment by iotamudelta** [comment]
Closing issue as not observed any longer by @Delaunay - please reopen if this issue is still observed
