### ISSUE TITLE
Memory access fault by GPU node-1 (Agent handle: 0x2fb8040) on address 0x541e00000. Reason: Page not present or supervisor privilege.

### ISSUE THREAD

**Issue by liamnr2** [ROCmSoftwarePlatform/pytorch#499]
MSG-GAN runs into a memory access fault at the start of training.

Docker image used: rocm/pytorch:rocm2.7_ubuntu18.04_py3.6_pytorch
Graphics card: RX 470
Code: https://github.com/akanimax/BBMSG-GAN
Additional pip requirements: scipy, tqdm, tensorboardX

Command line used:
`MIOPEN_DEBUG_GCN_ASM_KERNELS=0 python train.py --batch_size 1 --spoofing_factor 1 --images_dir /data/datasets/celebA`

MIOPEN_DEBUG_GCN_ASM_KERNELS=0 is required to sidestep this issue:
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/117

collect_env.py:
PyTorch version: 1.3.0a0+276bde3
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.3 LTS
GCC version: Could not collect
CMake version: version 3.6.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.3.0a0+276bde3
[pip3] torchvision==0.3.0a0+2b73a48
[conda] Could not collect

Output with MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_LOG_LEVEL=5:
[bmsggan_output.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/3693784/bmsggan_output_logging5.txt)

**Comment by Delaunay** [comment]
I took the last cmd that MIOpen was outputting and tested it on my RX580. 
It worked on my end. I am using the latest ROCm stack (with MIOpen 2.1.0-7487-rocm-rel-2.9-6-a5a4129).

```
/opt/rocm/miopen$ ./bin/MIOpenDriver conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpenDriver: conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpen Backward Data Conv. Algorithm: 0
GPU Kernel Time Backward Data Conv. Elapsed: 1.560938 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv3x3u1, 1, 1025, 3, 3, 1024, 4, 4,  302284800, 41984000, 65536, 194, 27, 1.560938
Backward Convolution Data Verifies on CPU and GPU (1.33189e-07)
```

## Open CL

```
/opt/rocm$ ./opencl/bin/x86_64/clinfo 
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (2982.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Ellesmere [Radeon RX 470/480/570/570X/580/580X]
  Device Topology:				 PCI[ B#37, D#0, F#0 ]
  Max compute units:				 36
```

## HIP
```
/opt/rocm$ ./bin/hipconfig
HIP version  : 2.8.19361-cbe6b65

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include -I/opt/rocm/hsa/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 10.0.0 (/data/jenkins_workspace/compute-rocm-rel-2.9/external/hcc-tot/clang fa40706d8ba0b8b958d42f579120eb9b89babc00) (/data/jenkins_workspace/compute-rocm-rel-2.9/external/hcc-tot/compiler b7f876231af7fdaf52e419088b8ba9e0c3a61845) (based on HCC 2.9.19392-75835c3-fa40706-b7f8762 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
  LLVM version 10.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/setepenre/.local/bin:/opt/anaconda3/x86_64/bin:/opt/anaconda3/x86_64/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64

== Linux Kernel
Hostname     : nas
Linux nas 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

```

**Comment by david-jk** [comment]
If I execute the command on its own, it also succeeds for me:
```
root@3b8ab3d38184:/opt/rocm/miopen# MIOPEN_DEBUG_GCN_ASM_KERNELS=0 ./bin/MIOpenDriver conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpenDriver: conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt
MIOpen Backward Data Conv. Algorithm: 0
GPU Kernel Time Backward Data Conv. Elapsed: 0.435297 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv3x3u1, 1, 1025, 3, 3, 1024, 4, 4,  302284800, 41984000, 65536, 694, 97, 0.435297
Backward Convolution Data Verifies on CPU and GPU (1.35201e-07)
```

That seems to suggest that it isn't caused by MIOpen directly and that it just happens to be the last output before the memory access fault.

**Comment by liamnr2** [comment]
When I execute this on its own, it also succeeds for me:
```
root@3b8ab3d38184:/opt/rocm/miopen# MIOPEN_DEBUG_GCN_ASM_KERNELS=0 ./bin/MIOpenDriver conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpenDriver: conv -n 1 -c 1025 -H 4 -W 4 -k 1024 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt
MIOpen Backward Data Conv. Algorithm: 0
GPU Kernel Time Backward Data Conv. Elapsed: 0.435297 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv3x3u1, 1, 1025, 3, 3, 1024, 4, 4,  302284800, 41984000, 65536, 694, 97, 0.435297
Backward Convolution Data Verifies on CPU and GPU (1.35201e-07)
```

That seems to suggest that the problem isn't caused by MIOpen directly and that it just happens to be the last output before the memory access fault occurs.

**Comment by liamnr2** [comment]
I just saw that new docker images are available and fortunately it now works on rocm2.9_ubuntu16.04_py3.6_pytorch.
